#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it under the
#  terms of the GNU Lesser General Public License as published by the Free
#  Software Foundation; either version 2.1 of the License, or (at your option)
#  any later version.

[Resolve]

DNS=1.1.1.1#cloudflare-dns.com 8.8.8.8#dns.google

FallbackDNS=1.0.0.1#cloudflare-dns.com 8.8.4.4#dns.google

DNSOverTLS=yes

DNSSEC=no

MulticastDNS=no

LLMNR=no

DNSStubListener=yes

Cache=yes
